### CSE-221710302060-Shaik Shoaib Aslam

#### Different ways to define modules
        1. import module
        2. import module as alias
        3. from module import ....
        4. from module import *

#### Numpy Module

In [1]:
import numpy as np
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [2]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
a2.ndim

2

In [5]:
a2.shape

(3, 3)

In [6]:
print(a2.shape[0])
print(a2.shape[1])

3
3


In [7]:
arr = np.array([1,2,3,4,5,6])
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
#Inserting elements using dynamically
a3 = np.array([],dtype = "int32")


In [13]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [14]:
a3 = np.append(a3,[34,56,78,45,32])
a3

array([12, 34, 56, 78, 45, 32])

#### Slicing

In [15]:
a3[3]

78

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1[1,2]

6

In [19]:
print(arr1[2:,:])

[[7 8 9]]


In [20]:
print(arr1[2:,0:2])

[[7 8]]


In [21]:
print(arr1[0:,0:2])

[[1 2]
 [4 5]
 [7 8]]


In [22]:
print(arr1[0,0:2])

[1 2]


In [23]:
print(arr1[0::2,:])

[[1 2 3]
 [7 8 9]]


In [25]:
for row in arr1:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [26]:
for ele in arr1.flat:
    print(ele)

1
2
3
4
5
6
7
8
9


### Indexing with boolean array

In [27]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
result = (arr1%2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [29]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending

In [31]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2))) # append vertically
print(np.hstack((arr1,arr2))) # append horizontally

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes
    1. size
    2. itemsize
    3. dtype
    4. ndim
    5. shape


In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr.size

10

In [34]:
arr.itemsize

4

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr.ndim

1

In [37]:
arr.shape

(10,)

### Built-in Functions
    1. zeros() 
    2. ones()      
    3. full()      
    4. eye()       
    5. linspace() 
    6. reshape()  
    7. ravel()    
    8. arange()

In [38]:
#zeros()
z = np.zeros((2,3),dtype = "int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [39]:
#ones()
o = np.ones((2,3),dtype = "int32")
o

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
#full()
f = np.full((2,3),"Sample")
print(f)

[['Sample' 'Sample' 'Sample']
 ['Sample' 'Sample' 'Sample']]


In [ ]:
#eye()
e = np.eye(3,dtype= "int32")
e

In [43]:
#linspace()
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
#ravel()
print(arr2.ravel())

[11 12 13 14 15 16 17 18 19]


### Functions:
    1. min()
    2. max()
    3. sum()
    4. sqrt()
    5. std()
    6. mean()
    7. median()


In [46]:
print(arr1.min())

1


In [47]:
print(arr1.max())

9


In [51]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
print(arr1.sum())
print(arr1.sum(axis = 1)) # sum of row elements
print(arr1.sum(axis = 0)) # sum of column elemetns

45
[ 6 15 24]
[12 15 18]


In [52]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [53]:
np.mean(arr1)

5.0

In [54]:
np.median(arr1)

5.0

In [55]:
np.std(arr1)

2.581988897471611

### Mathematical Operations :  +,-,/,*,%

In [57]:
arr1 = np.array([1,4,7,0,4,6,8])
arr2 = np.array([6,2,3,1,7,8,9])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 7  6 10  1 11 14 17]
[-5  2  4 -1 -3 -2 -1]
[ 6  8 21  0 28 48 72]
[0.16666667 2.         2.33333333 0.         0.57142857 0.75
 0.88888889]
[1 0 1 0 4 6 8]


In [59]:
#dot() for matrix multiplication
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [60]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying User-defined functions


In [61]:
list1 = list(range(1,11))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
#x/(x+1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091]

In [63]:
ar = np.array(list1)

In [64]:
f = np.vectorize(lambda x : x/(x+1))
f(arr1)

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286],
       [0.875     , 0.88888889, 0.9       ]])