### CSE-221710302060-Shaik Shoaib Aslam

In [7]:
from numpy import random
print(random.randint(1,100))
print(random.rand()) # 0-1 float numbers

58
0.7973228899810092


In [8]:
#creating n-dimensional arrays

print(random.randint(100,size = (3)))
print(random.randint(100,size = (3,3)))
print(random.randint(100,size = (4,4,2)))

[81 27  7]
[[49 44 92]
 [13  2 16]
 [ 0 20 41]]
[[[ 2 85]
  [89 79]
  [ 6 17]
  [ 8 76]]

 [[60 29]
  [20 99]
  [10 10]
  [22 66]]

 [[27 90]
  [95 58]
  [29 97]
  [52 66]]

 [[88 24]
  [ 9 45]
  [34 98]
  [ 3 21]]]


In [9]:
#creating n- dimensional array using float numbers
print(random.rand(3,3))

[[0.5903939  0.05900163 0.36013901]
 [0.83246462 0.49957485 0.4781186 ]
 [0.61575018 0.70650968 0.63670917]]


In [10]:
a = random.randint(100,size = (3,3)).ravel()
a

array([15, 74, 36, 64, 52, 52, 74, 88, 96])

In [12]:
random.choice(a)

36

In [13]:
# for generating an array for given size, shape and elements
random.choice([1,2,3,4,5],size = (4,4))

array([[5, 3, 1, 2],
       [5, 5, 5, 3],
       [2, 3, 2, 1],
       [2, 3, 2, 5]])

### Pandas
    1. Data Manipulation,analysis and data cleaning
    2. Tabular data,unlabelled

### Creating DataFrame 
        1. using multiple dictionary
        2. using single dictionary

In [21]:
import pandas as pd
import numpy as np
dict1 = {"a":1,"b":2,"c":3,"d":4,"e":5}
dict2  = {"a":6,"b":7,"c":8,"d":9,"e":10}
data = {"First":dict1,"Second":dict2}
df  = pd.DataFrame(data,dtype =np.int32)
df

First  Second
a      1       6
b      2       7
c      3       8
d      4       9
e      5      10

In [22]:
d1 = {"name":["Jack","Smith","Ryan"],"Address":["US","AUS","CAN"]}
df1 = pd.DataFrame(d1)
df1

name Address
0   Jack      US
1  Smith     AUS
2   Ryan     CAN

In [24]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11,12,13,14,15,16,17,18,19,20])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"First":s1,"Second":s2,"Third":s3}
df2 = pd.DataFrame(data)
df2

First  Second Third
0      1      11     a
1      2      12     b
2      3      13     c
3      4      14     d
4      5      15     e
5      6      16     f
6      7      17     g
7      8      18     h
8      9      19     i
9     10      20     j

### Selecting data from DataFrames
        1.loc
        2.iloc

In [25]:
df2["Second"]

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
Name: Second, dtype: int64

In [26]:
df2[["Second","Third"]]

Second Third
0      11     a
1      12     b
2      13     c
3      14     d
4      15     e
5      16     f
6      17     g
7      18     h
8      19     i
9      20     j

In [27]:
df2.loc[:,"First"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: First, dtype: int64

In [29]:
df2.loc[:,["First","Second"]]

First  Second
0      1      11
1      2      12
2      3      13
3      4      14
4      5      15
5      6      16
6      7      17
7      8      18
8      9      19
9     10      20

In [30]:
df2.loc[0:5,["First","Second"]]

First  Second
0      1      11
1      2      12
2      3      13
3      4      14
4      5      15
5      6      16

In [31]:
df2.iloc[:,1]

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
Name: Second, dtype: int64

In [32]:
df2.iloc[0:4,0:1]

First
0      1
1      2
2      3
3      4

### Retrieving Information from DataFrame

In [33]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   First   10 non-null     int64 
 1   Second  10 non-null     int64 
 2   Third   10 non-null     object
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


In [34]:
df2.shape

(10, 3)

In [35]:
df2.columns

Index(['First', 'Second', 'Third'], dtype='object')

In [36]:
df2.index

RangeIndex(start=0, stop=10, step=1)

### Viewing Data from DataFrame    
    1.head()
    2.tail()
    3.sample()

In [37]:
df2.head() # first 5 rows

First  Second Third
0      1      11     a
1      2      12     b
2      3      13     c
3      4      14     d
4      5      15     e

In [39]:
df2.head(2)

First  Second Third
0      1      11     a
1      2      12     b

In [41]:
df2.tail() # last 5 rows

First  Second Third
5      6      16     f
6      7      17     g
7      8      18     h
8      9      19     i
9     10      20     j

In [42]:
df2.sample()

First  Second Third
4      5      15     e

In [43]:
df2.describe()

First    Second
count  10.00000  10.00000
mean    5.50000  15.50000
std     3.02765   3.02765
min     1.00000  11.00000
25%     3.25000  13.25000
50%     5.50000  15.50000
75%     7.75000  17.75000
max    10.00000  20.00000

In [45]:
df2 = df2.rename(columns = {"First":"Column1",
                            "Second":"Column2",
                            "Third":"Column3"})

In [46]:
df2

Column1  Column2 Column3
0        1       11       a
1        2       12       b
2        3       13       c
3        4       14       d
4        5       15       e
5        6       16       f
6        7       17       g
7        8       18       h
8        9       19       i
9       10       20       j