### CSE-221710302060-Shaik Shoaib Aslam

In [1]:
#Question 1
import numpy as np
arr1 = np.arange(12,38)
print("Original array",arr1)
rev = arr1[::-1]
print("Reversed array :",rev)

Original array [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array : [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [94]:
#Question 2
n = int(input("Enter size :"))
z = np.ones((n,n))
z[1:n-1,1:n-1] = 0
z

Enter size :8


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [86]:
#Question 3
import numpy as np
arr = np.array([0,10,20,40,60])
arr1 = np.array([0,40])

res = np.isin(arr,arr1)     #isin function only returns boolean values 
print(res)

[ True False False  True False]


In [96]:
#Question 4
list1 = [int(i) for i in input().split()]
list2 = [int(i) for i in input().split()]
arr = np.array(list1)
arr1 = np.array(list2)
d = np.setdiff1d(arr1,arr)  # setdiff1d returns sorted and unique values in array1 that are not in array2.
d

10 30 40 50 70 90
0 10 20 40 60 80


array([ 0, 20, 60, 80])

In [93]:
#Question 5
list1=[int(i) for i in input().split()]
arr=np.array(list1)
matrix=np.diag(arr)  #diag constructs a diagonal array
matrix

4 5 6 8


array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])